version: "3"

services:
  dtrack:
    image: dependencytrack/bundled:4.8.2
    ports:
    - "127.0.0.1:8080:8080"
    restart: unless-stopped

  dtapac:
    build: ../../../
    environment:
      DTRACK_URL: "http://dtrack:8080"
      DTRACK_APIKEY: "changeme"
      OPA_URL: "http://opa:8181"
      WATCH_BUNDLE: "dtapac"
      FINDING_POLICY_PATH: "/dtapac/finding"
      VIOLATION_POLICY_PATH: "/dtapac/violation"
      LOG_LEVEL: "debug"
    ports:
    - "127.0.0.1:8081:8080"
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:0.56.0-rootless
    command:
    - run
    - --server
    # (Periodically) pull bundle from nginx
    - --set=services.bundleserver.url=http://nginx
    - --set=bundles.dtapac.service=bundleserver
    - --set=bundles.dtapac.resource=bundles/dtapac.tar.gz
    # Send status notifications to dtapac
    - --set=services.dtapac.url=http://dtapac:8080/api/v1/opa
    - --set=status.service=dtapac
    depends_on:
    - nginx
    ports:
    - "127.0.0.1:8181:8181"
    restart: unless-stopped

  nginx:
    image: nginx:1.25.2-alpine
    volumes:
    - "../../bundles:/usr/share/nginx/html/bundles:ro"
    restart: unless-stopped
